on: push
name: Main Workflow
jobs:
  artifactoryUpload:
    name: Upload Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0
    - name: build
      run: ./buildmyartifact.sh
    - name: publish to artifactory
      uses: advancedcsg-open/action-jfrog-cli@master
      with:
        url: 'https://alisaeed.jfrog.io/'
        credentials type: 'apikey'
        apikey: 'AKCp8mZn3SqbErr15JjvPT5R9fBY5bbgHabLmqn81ronf9ERuFkuoscBV4qbYvf3vgtPDAKLc'
        args: u "dist/*" "/mu/repo/path/" --recursive=true --build-name=myawesomeapp
