on: push
name: Main Workflow
jobs:
  artifactoryUpload:
    name: Upload Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    
    - name: publish to artifactory
      uses: advancedcsg-open/action-jfrog-cli@master
      with:
        url: 'https://alisaeed.jfrog.io/'
        credentials type: 'apikey'
        apikey: 'AKCp8mZn3SqbErr15JjvPT5R9fBY5bbgHabLmqn81ronf9ERuFkuoscBV4qbYvf3vgtPDAKLc'
        args: u "*.zip" "/artifactory/example-repo-local/" --recursive=false
